// Package skills keeps one canonical copy of each skill (skills/<name>/SKILL.md)
// and makes it usable across AI coding tools either by symlink (air skills link)
// or by generating per-tool copies (air skills sync). Claude uses the canonical
// format directly; Cursor/Copilot/Gemini need different frontmatter, so a single
// symlinked file shares the body but not each tool's trigger frontmatter.
package skills

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Skill is a canonical skill parsed from a SKILL.md.
type Skill struct {
	Name        string
	Description string
	Body        string
	Dir         string // canonical directory (holds SKILL.md + references/)
}

// Tools are the supported targets for sync/link.
var Tools = []string{"claude", "cursor", "copilot", "gemini"}

// toolFile returns the per-skill output path (relative to the out root) for the
// file-based tools. Claude is a directory, handled separately.
func toolFile(tool, name string) (string, bool) {
	switch tool {
	case "cursor":
		return filepath.Join(".cursor", "rules", name+".mdc"), true
	case "copilot":
		return filepath.Join(".github", "instructions", name+".instructions.md"), true
	case "gemini":
		return filepath.Join(".gemini", "skills", name+".md"), true
	}
	return "", false
}

func parseFrontmatter(content string) (description, body string) {
	s := strings.ReplaceAll(content, "\r\n", "\n")
	if !strings.HasPrefix(s, "---\n") {
		return "", strings.TrimSpace(s)
	}
	rest := s[len("---\n"):]
	end := strings.Index(rest, "\n---")
	if end < 0 {
		return "", strings.TrimSpace(s)
	}
	fm := rest[:end]
	body = strings.TrimLeft(rest[end+len("\n---"):], "\n")
	lines := strings.Split(fm, "\n")
	for i, line := range lines {
		if !strings.HasPrefix(strings.TrimSpace(line), "description:") {
			continue
		}
		val := strings.TrimSpace(strings.SplitN(line, ":", 2)[1])
		if isBlockScalar(val) {
			keyIndent := indentOf(line)
			var parts []string
			for _, next := range lines[i+1:] {
				if strings.TrimSpace(next) == "" {
					continue
				}
				if indentOf(next) <= keyIndent {
					break
				}
				parts = append(parts, strings.TrimSpace(next))
			}
			description = strings.Join(parts, " ")
		} else {
			description = strings.Trim(val, `"'`)
		}
		break
	}
	return description, strings.TrimSpace(body)
}

func isBlockScalar(v string) bool {
	switch v {
	case "", ">", ">-", ">+", "|", "|-", "|+":
		return true
	}
	return false
}

func indentOf(s string) int { return len(s) - len(strings.TrimLeft(s, " ")) }

// Discover loads every skill directory (one containing SKILL.md) under skillsDir.
func Discover(skillsDir string) ([]Skill, error) {
	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		return nil, fmt.Errorf("read skills dir %q: %w", skillsDir, err)
	}
	var out []Skill
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(skillsDir, e.Name())
		data, err := os.ReadFile(filepath.Join(dir, "SKILL.md"))
		if err != nil {
			continue
		}
		desc, body := parseFrontmatter(string(data))
		out = append(out, Skill{Name: e.Name(), Description: desc, Body: body, Dir: dir})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// Project returns the file content for a file-based tool (cursor/copilot/gemini).
func Project(tool string, s Skill) (content string, err error) {
	mark := fmt.Sprintf("<!-- generated by `air skills sync` from skills/%s/SKILL.md — edit the source, not this file -->", s.Name)
	switch tool {
	case "cursor":
		return fmt.Sprintf("---\ndescription: %s\nglobs:\nalwaysApply: false\n---\n\n%s\n\n%s\n", s.Description, mark, s.Body), nil
	case "copilot":
		return fmt.Sprintf("---\ndescription: %s\napplyTo: \"**\"\n---\n\n%s\n\n%s\n", s.Description, mark, s.Body), nil
	case "gemini":
		return fmt.Sprintf("# %s\n\n> %s\n\n%s\n\n%s\n", s.Name, s.Description, mark, s.Body), nil
	}
	return "", fmt.Errorf("unknown projectable tool %q", tool)
}

// Sync writes per-tool copies into outDir. Claude is copied as a full directory
// (SKILL.md + references); the others are projected single files.
func Sync(skillsDir, outDir string, tools []string) (map[string]int, error) {
	all, err := Discover(skillsDir)
	if err != nil {
		return nil, err
	}
	if len(all) == 0 {
		return nil, fmt.Errorf("no skills found under %q", skillsDir)
	}
	counts := map[string]int{}
	for _, tool := range tools {
		tool = strings.TrimSpace(tool)
		for _, s := range all {
			if tool == "claude" {
				if err := copyDir(s.Dir, filepath.Join(outDir, ".claude", "skills", s.Name)); err != nil {
					return nil, err
				}
				counts[tool]++
				continue
			}
			rel, ok := toolFile(tool, s.Name)
			if !ok {
				return nil, fmt.Errorf("unknown tool %q (want %s)", tool, strings.Join(Tools, ", "))
			}
			content, err := Project(tool, s)
			if err != nil {
				return nil, err
			}
			if err := writeFile(filepath.Join(outDir, rel), content); err != nil {
				return nil, err
			}
			counts[tool]++
		}
		if tool == "gemini" {
			writeGeminiIndex(outDir, all)
		}
	}
	return counts, nil
}

// Link points each tool location at the canonical skills via symlinks: Claude is
// one directory symlink; the others are per-skill file symlinks (body shared,
// per-tool frontmatter not). Returns counts, or an error if the OS refuses
// symlinks (e.g. Windows without Developer Mode) — fall back to Sync.
func Link(skillsDir, outDir string, tools []string) (map[string]int, error) {
	all, err := Discover(skillsDir)
	if err != nil {
		return nil, err
	}
	counts := map[string]int{}
	for _, tool := range tools {
		tool = strings.TrimSpace(tool)
		if tool == "claude" {
			link := filepath.Join(outDir, ".claude", "skills")
			if err := symlinkRel(skillsDir, link); err != nil {
				return nil, err
			}
			counts[tool]++
			continue
		}
		for _, s := range all {
			rel, ok := toolFile(tool, s.Name)
			if !ok {
				return nil, fmt.Errorf("unknown tool %q (want %s)", tool, strings.Join(Tools, ", "))
			}
			if err := symlinkRel(filepath.Join(s.Dir, "SKILL.md"), filepath.Join(outDir, rel)); err != nil {
				return nil, err
			}
			counts[tool]++
		}
	}
	return counts, nil
}

// symlinkRel creates link -> target using a relative target for portability,
// replacing any existing entry.
func symlinkRel(target, link string) error {
	if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
		return err
	}
	rel, err := filepath.Rel(filepath.Dir(link), target)
	if err != nil {
		rel = target
	}
	_ = os.RemoveAll(link)
	if err := os.Symlink(rel, link); err != nil {
		return fmt.Errorf("symlink %s -> %s: %w (use `air skills sync` if symlinks are unavailable)", link, rel, err)
	}
	return nil
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func copyDir(src, dst string) error {
	return filepath.Walk(src, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, p)
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		return copyFile(p, target)
	})
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

func writeGeminiIndex(outDir string, all []Skill) {
	var b strings.Builder
	b.WriteString("# Skills (Gemini)\n\nReference a skill on demand: `@.gemini/skills/<name>.md`\n\n")
	for _, s := range all {
		fmt.Fprintf(&b, "- **%s** — %s\n", s.Name, s.Description)
	}
	_ = writeFile(filepath.Join(outDir, ".gemini", "skills", "INDEX.md"), b.String())
}
